import { IMG } from "./images";
import type { BlogPost } from "./types";

export const blogPosts: BlogPost[] = [
  {
    slug: "how-to-clean-bathroom",
    title: "How to Clean Your Bathroom: A Step-by-Step Guide",
    titleHi: "बाथरूम कैसे साफ करें: स्टेप-बाय-स्टेप गाइड",
    excerpt:
      "A clean bathroom is the heart of a hygienic home. Follow this simple, room-by-room routine to keep every surface sparkling and germ-free.",
    excerptHi:
      "साफ बाथरूम स्वच्छ घर का दिल है। यह आसान रूटीन अपनाएँ और हर सतह को चमकदार और कीटाणु-मुक्त रखें।",
    category: "Bathroom",
    categoryHi: "बाथरूम",
    author: "DPT Home Care Team",
    date: "2025-01-12",
    readTime: "6 min read",
    readTimeHi: "6 मिनट",
    image: IMG.bathroomTiles,
    keywords: ["how to clean bathroom", "bathroom cleaning guide", "toilet cleaning", "bathroom hygiene"],
    content: [
      { type: "p", text: "The bathroom is one of the most used — and most germ-prone — rooms in any home. Soap scum, hard-water stains and bacteria build up quickly, but with the right products and a simple routine, you can keep it spotless in under 20 minutes. Here's exactly how the professionals do it.", textHi: "बाथरूम घर का सबसे ज़्यादा इस्तेमाल होने वाला — और कीटाणुओं के लिहाज़ से सबसे संवेदनशील — कमरा है। साबुन की परत, हार्ड-वाटर के दाग और बैक्टीरिया तेज़ी से जमा होते हैं, लेकिन सही प्रोडक्ट्स और एक आसान रूटीन के साथ आप इसे 20 मिनट से भी कम में बेदाग रख सकते हैं। प्रोफेशनल्स ठीक ऐसे ही करते हैं।" },
      { type: "h2", text: "Start from the top, work downwards", textHi: "ऊपर से शुरू करें, नीचे की ओर बढ़ें" },
      { type: "p", text: "Always clean from the highest point to the lowest so that dust and drips fall onto areas you haven't cleaned yet. Begin with mirrors and shelves, move to tiles and fittings, then finish with the toilet and floor.", textHi: "हमेशा सबसे ऊँची जगह से सफाई शुरू करें और नीचे की ओर आएँ, ताकि धूल और पानी की बूँदें उन्हीं जगहों पर गिरें जो अभी साफ होनी बाकी हैं। पहले शीशे और शेल्फ, फिर टाइल्स और फिटिंग्स, और आख़िर में टॉयलेट और फर्श।" },
      { type: "h2", text: "Step-by-step bathroom cleaning routine", textHi: "स्टेप-बाय-स्टेप बाथरूम क्लीनिंग रूटीन" },
      { type: "ol", items: [
        "Clear the space: remove bottles, mats and bins so every surface is accessible.",
        "Spray the mirror with DPT Glass Cleaner and wipe with a dry microfibre cloth for a streak-free shine.",
        "Apply DPT Bathroom Cleaner to tiles, the wash basin, taps and shower. Leave it for 2–3 minutes to dissolve soap scum.",
        "Scrub gently and rinse to reveal the original shine of your fittings.",
        "Apply DPT Toilet Cleaner around and under the rim, leave for 5–10 minutes, then scrub and flush.",
        "Finally, mop the floor with diluted DPT Floor Cleaner for a disinfected, fragrant finish.",
      ], itemsHi: [
        "जगह खाली करें: बोतलें, मैट और डस्टबिन हटा दें ताकि हर सतह तक पहुँच आसान हो।",
        "शीशे पर DPT Glass Cleaner स्प्रे करें और सूखे माइक्रोफाइबर कपड़े से पोंछें — बिना धारियों वाली चमक के लिए।",
        "टाइल्स, वॉश बेसिन, नल और शॉवर पर DPT Bathroom Cleaner लगाएँ। साबुन की परत घुलने के लिए इसे 2–3 मिनट छोड़ दें।",
        "हल्के हाथ से रगड़ें और धो दें — फिटिंग्स की असली चमक लौट आएगी।",
        "रिम के चारों ओर और नीचे DPT Toilet Cleaner लगाएँ, 5–10 मिनट छोड़ें, फिर ब्रश करें और फ्लश करें।",
        "आख़िर में, पानी में घोलकर DPT Floor Cleaner से फर्श पर पोछा लगाएँ — डिसइंफेक्टेड, खुशबूदार फिनिश के लिए।",
      ]},
      { type: "h2", text: "Don't forget these hidden germ hotspots", textHi: "कीटाणुओं के इन छिपे ठिकानों को न भूलें" },
      { type: "ul", items: [
        "Taps and handles — touched constantly, cleaned rarely.",
        "The underside of the toilet seat and the flush button.",
        "Shower drains, where hair and residue collect.",
        "The gap between tiles, where grime and mould hide.",
      ], itemsHi: [
        "नल और हैंडल — इन्हें बार-बार छुआ जाता है, पर सफाई कभी-कभार ही होती है।",
        "टॉयलेट सीट का निचला हिस्सा और फ्लश बटन।",
        "शॉवर की नालियाँ, जहाँ बाल और गंदगी जमा होती है।",
        "टाइल्स के बीच की जगह, जहाँ मैल और फफूंदी छिपी रहती है।",
      ]},
      { type: "quote", text: "A bathroom that looks clean isn't always hygienic. Disinfecting the surfaces you touch most is what truly protects your family.", textHi: "जो बाथरूम साफ दिखता है, वह ज़रूरी नहीं कि हाइजीनिक भी हो। जिन सतहों को आप सबसे ज़्यादा छूते हैं, उन्हें डिसइंफेक्ट करना ही आपके परिवार की असली सुरक्षा है।" },
      { type: "h2", text: "How often should you clean?", textHi: "कितनी बार सफाई करनी चाहिए?" },
      { type: "p", text: "Wipe surfaces and the mirror daily, do a full clean twice a week, and deep-clean grout and drains once a month. Consistency beats intensity — a quick daily wipe keeps the weekly clean effortless.", textHi: "सतहों और शीशे को रोज़ पोंछें, हफ्ते में दो बार पूरी सफाई करें, और महीने में एक बार ग्राउट और नालियों की डीप-क्लीनिंग करें। नियमितता ही असली ताकत है — रोज़ की झटपट सफाई हफ्ते की बड़ी सफाई को आसान बना देती है।" },
      { type: "p", text: "With DPT Home Care's complete bathroom range — glass cleaner, bathroom cleaner and toilet cleaner — you have everything you need for a spotless, germ-free washroom that stays fresh for longer.", textHi: "DPT Home Care की पूरी बाथरूम रेंज — ग्लास क्लीनर, बाथरूम क्लीनर और टॉयलेट क्लीनर — के साथ आपके पास वह सब कुछ है जो एक बेदाग, कीटाणु-मुक्त और देर तक ताज़ा रहने वाले वॉशरूम के लिए चाहिए।" },
    ],
  },
  {
    slug: "best-floor-cleaner",
    title: "How to Choose the Best Floor Cleaner for Your Home",
    titleHi: "अपने घर के लिए सबसे अच्छा फ्लोर क्लीनर कैसे चुनें",
    excerpt:
      "Not all floor cleaners are equal. Learn how to pick the right one for your flooring type and get a spotless, disinfected, long-lasting shine.",
    excerptHi:
      "हर फ्लोर क्लीनर एक जैसा नहीं होता। जानें कि अपने फर्श के हिसाब से सही क्लीनर कैसे चुनें और पाएँ बेदाग, डिसइंफेक्टेड, देर तक टिकने वाली चमक।",
    category: "Floor Care",
    categoryHi: "फ्लोर केयर",
    author: "DPT Home Care Team",
    date: "2025-02-04",
    readTime: "5 min read",
    readTimeHi: "5 मिनट",
    image: IMG.tiledFloor,
    keywords: ["best floor cleaner", "floor cleaner for tiles", "marble floor cleaner", "disinfectant floor cleaner"],
    content: [
      { type: "p", text: "Your floor is the largest surface in your home and the first thing guests notice. The right floor cleaner does three jobs at once: it removes dirt, kills germs and leaves a lasting fragrance — without damaging your flooring. Here's how to choose wisely.", textHi: "फर्श आपके घर की सबसे बड़ी सतह है और मेहमानों की नज़र सबसे पहले उसी पर पड़ती है। सही फ्लोर क्लीनर एक साथ तीन काम करता है: गंदगी हटाता है, कीटाणु मारता है और देर तक टिकने वाली खुशबू छोड़ता है — वह भी आपके फर्श को नुकसान पहुँचाए बिना। समझदारी से चुनाव ऐसे करें।" },
      { type: "h2", text: "Match the cleaner to your floor type", textHi: "फर्श के प्रकार के हिसाब से क्लीनर चुनें" },
      { type: "ul", items: [
        "Marble & granite: use a pH-balanced, non-acidic cleaner to protect the natural stone.",
        "Ceramic & vitrified tiles: almost any quality cleaner works; look for streak-free formulas.",
        "Wooden floors: use a heavily diluted solution and a well-wrung mop to avoid water damage.",
      ], itemsHi: [
        "मार्बल और ग्रेनाइट: प्राकृतिक पत्थर की सुरक्षा के लिए pH-बैलेंस्ड, नॉन-एसिडिक क्लीनर इस्तेमाल करें।",
        "सिरेमिक और विट्रिफाइड टाइल्स: लगभग हर अच्छी क्वालिटी का क्लीनर चलेगा; बिना धारियाँ छोड़ने वाला फॉर्मूला चुनें।",
        "लकड़ी के फर्श: पानी से नुकसान न हो, इसके लिए खूब पतला घोल और अच्छी तरह निचोड़ा हुआ पोछा इस्तेमाल करें।",
      ]},
      { type: "h2", text: "Look for these key qualities", textHi: "इन ख़ास खूबियों पर ध्यान दें" },
      { type: "ol", items: [
        "Strong disinfectant action against germs.",
        "A concentrated formula, so you use less per bucket and save money.",
        "A no-rinse, no-residue finish that dries without stickiness.",
        "A long-lasting fragrance that keeps rooms fresh for hours.",
      ], itemsHi: [
        "कीटाणुओं के खिलाफ दमदार डिसइंफेक्टेंट असर।",
        "कॉन्सेंट्रेटेड फॉर्मूला, ताकि हर बाल्टी में कम लगे और पैसे बचें।",
        "बिना धोए, बिना अवशेष वाली फिनिश जो चिपचिपाहट छोड़े बिना सूख जाए।",
        "देर तक टिकने वाली खुशबू जो कमरों को घंटों तरोताज़ा रखे।",
      ]},
      { type: "h2", text: "Why concentration matters", textHi: "कॉन्सेंट्रेशन क्यों मायने रखता है" },
      { type: "p", text: "A concentrated cleaner like DPT Floor Cleaner needs only one capful per bucket of water. That means a single bottle lasts far longer than diluted supermarket brands — better cleaning at a lower cost per wash.", textHi: "DPT Floor Cleaner जैसे कॉन्सेंट्रेटेड क्लीनर की एक बाल्टी पानी में सिर्फ एक ढक्कन काफी है। यानी एक बोतल पतले सुपरमार्केट ब्रांड्स से कहीं ज़्यादा चलती है — हर पोछे पर कम खर्च में बेहतर सफाई।" },
      { type: "quote", text: "The best floor cleaner isn't the cheapest bottle — it's the one that gives you the most clean, germ-free washes for your money.", textHi: "सबसे अच्छा फ्लोर क्लीनर सबसे सस्ती बोतल नहीं होती — वह होता है जो आपके पैसों में सबसे ज़्यादा साफ, कीटाणु-मुक्त पोछे दे।" },
      { type: "h2", text: "Our recommendation", textHi: "हमारी सलाह" },
      { type: "p", text: "DPT Floor Cleaner is safe on marble, granite, tiles and vitrified floors, disinfects as it cleans, and comes in Floral, Citrus, Jasmine and Lavender fragrances. For institutions and large areas, our concentrated Phenyl offers powerful, economical disinfection.", textHi: "DPT Floor Cleaner मार्बल, ग्रेनाइट, टाइल्स और विट्रिफाइड फर्श पर पूरी तरह सुरक्षित है, सफाई के साथ-साथ डिसइंफेक्ट भी करता है, और फ्लोरल, सिट्रस, जैस्मिन और लैवेंडर खुशबुओं में मिलता है। संस्थानों और बड़ी जगहों के लिए हमारा कॉन्सेंट्रेटेड Phenyl दमदार, किफायती डिसइंफेक्शन देता है।" },
    ],
  },
  {
    slug: "kitchen-cleaning-tips",
    title: "10 Kitchen Cleaning Tips for a Spotless, Hygienic Kitchen",
    titleHi: "बेदाग, हाइजीनिक किचन के लिए 10 किचन क्लीनिंग टिप्स",
    excerpt:
      "Grease, food stains and clutter make the kitchen the hardest room to clean. These 10 practical tips keep yours hygienic and shining every day.",
    excerptHi:
      "चिकनाई, खाने के दाग और बिखराव किचन को साफ रखने के लिहाज़ से सबसे मुश्किल कमरा बना देते हैं। ये 10 काम की टिप्स आपके किचन को रोज़ हाइजीनिक और चमकदार रखेंगी।",
    category: "Kitchen",
    categoryHi: "किचन",
    author: "DPT Home Care Team",
    date: "2025-02-20",
    readTime: "6 min read",
    readTimeHi: "6 मिनट",
    image: IMG.kitchenSurface,
    keywords: ["kitchen cleaning tips", "how to clean kitchen", "degreaser", "kitchen hygiene"],
    content: [
      { type: "p", text: "The kitchen is where hygiene matters most — it's where your family's food is prepared. Yet grease, spills and food residue make it the toughest room to keep clean. These ten expert tips will help you maintain a spotless, food-safe kitchen with minimal effort.", textHi: "किचन वह जगह है जहाँ हाइजीन सबसे ज़्यादा मायने रखती है — यहीं आपके परिवार का खाना बनता है। लेकिन चिकनाई, छलकन और खाने के अवशेष इसे साफ रखने के लिहाज़ से सबसे मुश्किल कमरा बना देते हैं। ये दस एक्सपर्ट टिप्स कम मेहनत में बेदाग, फूड-सेफ किचन बनाए रखने में आपकी मदद करेंगी।" },
      { type: "h2", text: "Daily habits that keep grease away", textHi: "रोज़ की आदतें जो चिकनाई को दूर रखती हैं" },
      { type: "ol", items: [
        "Wipe the countertop and stove after every meal, while spills are still fresh and easy to remove.",
        "Wash utensils immediately with DPT Dish Wash Liquid to stop grease from hardening.",
        "Clean the sink daily — it holds more bacteria than most people realise.",
        "Empty and rinse the dustbin every night to prevent odour and pests.",
        "Keep a spray bottle of DPT Kitchen Cleaner handy for instant degreasing.",
      ], itemsHi: [
        "हर खाने के बाद काउंटरटॉप और चूल्हा पोंछ दें, जब छलकन ताज़ा हो और आसानी से निकल जाए।",
        "बर्तनों को तुरंत DPT Dish Wash Liquid से धोएँ ताकि चिकनाई जमकर सख्त न हो।",
        "सिंक रोज़ साफ करें — इसमें जितना लोग समझते हैं उससे कहीं ज़्यादा बैक्टीरिया होते हैं।",
        "बदबू और कीड़ों से बचने के लिए डस्टबिन हर रात खाली करके धो लें।",
        "तुरंत चिकनाई हटाने के लिए DPT Kitchen Cleaner की स्प्रे बोतल हाथ के पास रखें।",
      ]},
      { type: "h2", text: "Weekly deep-cleaning tasks", textHi: "हफ्तेवार डीप-क्लीनिंग के काम" },
      { type: "ol", items: [
        "Degrease the chimney and exhaust filter, where oil builds up fastest.",
        "Wipe down cabinet fronts and handles, common touchpoints for grease and germs.",
        "Clean the tiles behind the stove with a degreaser to remove oil splatter.",
        "Disinfect the fridge handles and shelves.",
        "Mop the floor with a disinfectant floor cleaner to finish.",
      ], itemsHi: [
        "चिमनी और एग्ज़ॉस्ट फिल्टर की चिकनाई साफ करें, जहाँ तेल सबसे तेज़ी से जमता है।",
        "कैबिनेट के दरवाज़े और हैंडल पोंछें — ये चिकनाई और कीटाणुओं के आम ठिकाने हैं।",
        "चूल्हे के पीछे की टाइल्स को डीग्रीज़र से साफ करें ताकि तेल के छींटे निकल जाएँ।",
        "फ्रिज के हैंडल और शेल्फ डिसइंफेक्ट करें।",
        "अंत में डिसइंफेक्टेंट फ्लोर क्लीनर से फर्श पर पोछा लगाएँ।",
      ]},
      { type: "h2", text: "The secret to cutting through grease", textHi: "चिकनाई काटने का राज़" },
      { type: "p", text: "Baked-on grease needs contact time. Spray DPT Kitchen Cleaner, wait one to two minutes, then wipe — no hard scrubbing required. For utensils, a lemon-based dish wash liquid dissolves oil far faster than plain soap.", textHi: "जमी हुई चिकनाई को कॉन्टैक्ट टाइम चाहिए। DPT Kitchen Cleaner स्प्रे करें, एक-दो मिनट रुकें, फिर पोंछ दें — ज़ोर से रगड़ने की ज़रूरत नहीं। बर्तनों के लिए, नींबू वाला डिश वॉश लिक्विड सादे साबुन से कहीं तेज़ी से तेल घोल देता है।" },
      { type: "quote", text: "A clean kitchen isn't about scrubbing harder — it's about cleaning smarter, and cleaning little and often.", textHi: "साफ किचन का मतलब ज़्यादा ज़ोर से रगड़ना नहीं — बल्कि समझदारी से, थोड़ा-थोड़ा और बार-बार साफ करना है।" },
      { type: "p", text: "Always rinse food-contact surfaces with clean water after using any cleaner. With DPT's kitchen range, you get powerful degreasing that keeps your kitchen hygienic and shining.", textHi: "किसी भी क्लीनर के इस्तेमाल के बाद खाने के संपर्क में आने वाली सतहों को साफ पानी से ज़रूर धोएँ। DPT की किचन रेंज के साथ आपको मिलती है दमदार डीग्रीज़िंग जो आपके किचन को हाइजीनिक और चमकदार रखती है।" },
    ],
  },
  {
    slug: "home-hygiene-guide",
    title: "The Complete Home Hygiene Guide for a Healthier Family",
    titleHi: "स्वस्थ परिवार के लिए संपूर्ण होम हाइजीन गाइड",
    excerpt:
      "Home hygiene is your family's first line of defence against illness. This complete guide covers every room and every essential habit.",
    excerptHi:
      "घर की हाइजीन बीमारियों के खिलाफ आपके परिवार की पहली सुरक्षा है। इस पूरी गाइड में हर कमरे और हर ज़रूरी आदत की बात है।",
    category: "Hygiene",
    categoryHi: "हाइजीन",
    author: "DPT Home Care Team",
    date: "2025-03-08",
    readTime: "7 min read",
    readTimeHi: "7 मिनट",
    image: IMG.family,
    keywords: ["home hygiene", "household hygiene guide", "healthy home", "germ protection"],
    content: [
      { type: "p", text: "A hygienic home is a healthy home. Germs spread through the surfaces we touch, the air we breathe and the hands we shake. This complete guide walks you through building a hygiene routine that protects everyone under your roof — without turning cleaning into a full-time job.", textHi: "हाइजीनिक घर ही स्वस्थ घर है। कीटाणु उन सतहों से फैलते हैं जिन्हें हम छूते हैं, उस हवा से जिसमें हम साँस लेते हैं और उन हाथों से जो हम मिलाते हैं। यह पूरी गाइड आपको ऐसा हाइजीन रूटीन बनाना सिखाती है जो आपके घर के हर सदस्य की रक्षा करे — बिना सफाई को फुल-टाइम काम बनाए।" },
      { type: "h2", text: "Focus on high-touch surfaces", textHi: "ज़्यादा छुई जाने वाली सतहों पर ध्यान दें" },
      { type: "p", text: "Most germs spread through frequently touched surfaces. Disinfect these daily, especially during flu season:", textHi: "ज़्यादातर कीटाणु बार-बार छुई जाने वाली सतहों से फैलते हैं। इन्हें रोज़ डिसइंफेक्ट करें, खासकर फ्लू के मौसम में:" },
      { type: "ul", items: [
        "Door handles, switches and remote controls.",
        "Taps, flush buttons and toilet seats.",
        "Dining tables and kitchen counters.",
        "Mobile phones and children's toys.",
      ], itemsHi: [
        "दरवाज़ों के हैंडल, स्विच और रिमोट कंट्रोल।",
        "नल, फ्लश बटन और टॉयलेट सीट।",
        "डाइनिंग टेबल और किचन काउंटर।",
        "मोबाइल फोन और बच्चों के खिलौने।",
      ]},
      { type: "h2", text: "Room-by-room hygiene essentials", textHi: "कमरे-दर-कमरे हाइजीन की ज़रूरी बातें" },
      { type: "h3", text: "Kitchen", textHi: "किचन" },
      { type: "p", text: "Wash utensils promptly, degrease surfaces and disinfect the sink daily. Food hygiene starts with a clean kitchen.", textHi: "बर्तन तुरंत धोएँ, सतहों की चिकनाई हटाएँ और सिंक को रोज़ डिसइंफेक्ट करें। खाने की हाइजीन साफ किचन से ही शुरू होती है।" },
      { type: "h3", text: "Bathroom", textHi: "बाथरूम" },
      { type: "p", text: "Use a disinfectant toilet cleaner and bathroom cleaner regularly, and keep a fresh hand wash at every basin.", textHi: "डिसइंफेक्टेंट टॉयलेट क्लीनर और बाथरूम क्लीनर का नियमित इस्तेमाल करें, और हर बेसिन पर ताज़ा हैंड वॉश रखें।" },
      { type: "h3", text: "Living areas", textHi: "लिविंग एरिया" },
      { type: "p", text: "Dust and mop floors with a disinfectant cleaner, and keep the air fresh with a quality room freshener.", textHi: "धूल झाड़ें, डिसइंफेक्टेंट क्लीनर से फर्श पर पोछा लगाएँ, और अच्छी क्वालिटी के रूम फ्रेशनर से हवा को तरोताज़ा रखें।" },
      { type: "h2", text: "Hand hygiene is non-negotiable", textHi: "हाथों की हाइजीन में कोई समझौता नहीं" },
      { type: "p", text: "Hand washing remains the single most effective way to prevent the spread of infection. Keep a moisturising hand wash at every sink and a sanitizer near the entrance for when soap and water aren't available.", textHi: "संक्रमण को फैलने से रोकने का सबसे असरदार तरीका आज भी हाथ धोना ही है। हर सिंक पर मॉइस्चराइज़िंग हैंड वॉश रखें और दरवाज़े के पास सैनिटाइज़र, ताकि साबुन-पानी न होने पर भी काम चल जाए।" },
      { type: "quote", text: "You can't see germs — which is exactly why a consistent hygiene routine matters more than an occasional deep clean.", textHi: "कीटाणु दिखाई नहीं देते — इसीलिए कभी-कभार की डीप क्लीनिंग से ज़्यादा ज़रूरी है एक नियमित हाइजीन रूटीन।" },
      { type: "h2", text: "Build a simple, repeatable routine", textHi: "एक आसान, दोहराने लायक रूटीन बनाएँ" },
      { type: "p", text: "The goal isn't perfection; it's consistency. A few daily habits — wiping surfaces, washing hands and keeping rooms fresh — protect your family far better than one big monthly clean. DPT Home Care's complete range makes building that routine simple and affordable.", textHi: "लक्ष्य परफेक्शन नहीं, नियमितता है। कुछ रोज़ की आदतें — सतहें पोंछना, हाथ धोना और कमरों को तरोताज़ा रखना — आपके परिवार की रक्षा महीने की एक बड़ी सफाई से कहीं बेहतर करती हैं। DPT Home Care की पूरी रेंज इस रूटीन को आसान और किफायती बना देती है।" },
    ],
  },
  {
    slug: "how-to-remove-tough-stains",
    title: "How to Remove Tough Stains: The Ultimate Guide",
    titleHi: "ज़िद्दी दाग कैसे हटाएँ: सबसे काम की गाइड",
    excerpt:
      "From oil and ink to hard-water marks and rust, this guide shows you how to tackle the most stubborn stains around your home.",
    excerptHi:
      "तेल और स्याही से लेकर हार्ड-वाटर के निशान और जंग तक — यह गाइड बताती है कि घर के सबसे ज़िद्दी दागों से कैसे निपटें।",
    category: "Stain Removal",
    categoryHi: "दाग हटाना",
    author: "DPT Home Care Team",
    date: "2025-03-25",
    readTime: "6 min read",
    readTimeHi: "6 मिनट",
    image: "/brand/blog-stain-removal-v3.jpg",
    keywords: ["how to remove tough stains", "stain removal", "hard water stains", "grease stain remover"],
    content: [
      { type: "p", text: "Every home battles stubborn stains — grease on the stove, hard-water marks in the bathroom, ink on the sofa. The key to winning is knowing which product to use and giving it enough contact time. Here's your room-by-room stain-removal playbook.", textHi: "हर घर ज़िद्दी दागों से जूझता है — चूल्हे पर चिकनाई, बाथरूम में हार्ड-वाटर के निशान, सोफे पर स्याही। जीत की कुंजी है सही प्रोडक्ट चुनना और उसे पर्याप्त कॉन्टैक्ट टाइम देना। पेश है आपकी कमरे-दर-कमरे दाग हटाने की गाइड।" },
      { type: "h2", text: "The golden rule: act fast", textHi: "सुनहरा नियम: तुरंत कदम उठाएँ" },
      { type: "p", text: "Fresh stains are always easier to remove than dried ones. Blot spills immediately (don't rub, which spreads them) and treat them before they set.", textHi: "ताज़ा दाग हमेशा सूखे दागों से आसानी से निकलते हैं। कुछ छलके तो उसे तुरंत सोख लें (रगड़ें नहीं, इससे दाग फैलता है) और जमने से पहले ही उस पर काम करें।" },
      { type: "h2", text: "Common stains and how to beat them", textHi: "आम दाग और उनसे निपटने के तरीके" },
      { type: "h3", text: "Grease and oil", textHi: "चिकनाई और तेल" },
      { type: "p", text: "Spray a degreasing kitchen cleaner, wait two minutes, then wipe. For fabric, apply a little dish wash liquid to the spot before washing.", textHi: "डीग्रीज़िंग किचन क्लीनर स्प्रे करें, दो मिनट रुकें, फिर पोंछ दें। कपड़े के लिए, धोने से पहले दाग पर थोड़ा डिश वॉश लिक्विड लगाएँ।" },
      { type: "h3", text: "Hard-water and limescale marks", textHi: "हार्ड-वाटर और लाइमस्केल के निशान" },
      { type: "p", text: "These white, chalky deposits respond to an acidic bathroom or toilet cleaner. Apply, leave for a few minutes, then scrub gently.", textHi: "ये सफेद, खड़िया जैसे जमाव एसिडिक बाथरूम या टॉयलेट क्लीनर से निकल जाते हैं। लगाएँ, कुछ मिनट छोड़ें, फिर हल्के हाथ से रगड़ें।" },
      { type: "h3", text: "Rust and yellow toilet stains", textHi: "जंग और टॉयलेट के पीले दाग" },
      { type: "p", text: "A thick toilet cleaner that clings to the surface works best. Leave it on for 10–15 minutes before scrubbing.", textHi: "गाढ़ा टॉयलेट क्लीनर जो सतह पर चिपका रहे, सबसे अच्छा काम करता है। ब्रश करने से पहले इसे 10–15 मिनट लगा रहने दें।" },
      { type: "h3", text: "Fabric stains", textHi: "कपड़ों के दाग" },
      { type: "p", text: "Pre-soak in a liquid detergent solution, then wash. Liquid detergent penetrates fibres better than powder and leaves no residue.", textHi: "लिक्विड डिटर्जेंट के घोल में पहले भिगोएँ, फिर धोएँ। लिक्विड डिटर्जेंट पाउडर से बेहतर रेशों में उतरता है और कोई अवशेष नहीं छोड़ता।" },
      { type: "ul", items: [
        "Always test on a small hidden area first.",
        "Never mix different cleaning chemicals together.",
        "Give the product time to work — patience beats scrubbing.",
        "Rinse thoroughly after treating any stain.",
      ], itemsHi: [
        "पहले हमेशा किसी छोटी, छिपी जगह पर टेस्ट करें।",
        "अलग-अलग सफाई के केमिकल कभी आपस में न मिलाएँ।",
        "प्रोडक्ट को काम करने का समय दें — रगड़ने से ज़्यादा सब्र काम आता है।",
        "किसी भी दाग का इलाज करने के बाद अच्छी तरह धो लें।",
      ]},
      { type: "quote", text: "The right cleaner and a little patience will remove almost any stain — harsh scrubbing usually just damages the surface.", textHi: "सही क्लीनर और थोड़ा सब्र लगभग हर दाग हटा देता है — ज़ोर से रगड़ने से अक्सर सतह ही खराब होती है।" },
      { type: "p", text: "With DPT Home Care's specialised range, you have the right formula for every kind of stain, from kitchen grease to bathroom limescale.", textHi: "DPT Home Care की स्पेशलाइज़्ड रेंज के साथ आपके पास हर तरह के दाग का सही फॉर्मूला है — किचन की चिकनाई से लेकर बाथरूम के लाइमस्केल तक।" },
    ],
  },
  {
    slug: "office-cleaning-tips",
    title: "Office Cleaning Tips for a Healthier, More Productive Workplace",
    titleHi: "स्वस्थ, ज़्यादा प्रोडक्टिव वर्कप्लेस के लिए ऑफिस क्लीनिंग टिप्स",
    excerpt:
      "A clean office reduces sick days and boosts productivity. Use these practical tips to keep your workplace hygienic and professional.",
    excerptHi:
      "साफ ऑफिस बीमारी की छुट्टियाँ घटाता है और प्रोडक्टिविटी बढ़ाता है। इन काम की टिप्स से अपने वर्कप्लेस को हाइजीनिक और प्रोफेशनल रखें।",
    category: "Office",
    categoryHi: "ऑफिस",
    author: "DPT Home Care Team",
    date: "2025-04-10",
    readTime: "5 min read",
    readTimeHi: "5 मिनट",
    image: IMG.ppeDisinfect,
    keywords: ["office cleaning tips", "workplace hygiene", "commercial cleaning", "office sanitization"],
    content: [
      { type: "p", text: "A clean workplace does more than look professional — it directly affects employee health, morale and productivity. Shared desks, keyboards and door handles are germ highways. Here's how to keep your office hygienic and your team healthy.", textHi: "साफ वर्कप्लेस सिर्फ प्रोफेशनल नहीं दिखता — यह कर्मचारियों की सेहत, हौसले और प्रोडक्टिविटी पर सीधा असर डालता है। साझा डेस्क, कीबोर्ड और दरवाज़ों के हैंडल कीटाणुओं के हाईवे हैं। जानिए अपने ऑफिस को हाइजीनिक और टीम को स्वस्थ कैसे रखें।" },
      { type: "h2", text: "Prioritise shared touchpoints", textHi: "साझा टचपॉइंट्स को प्राथमिकता दें" },
      { type: "p", text: "In an office, germs spread fastest through surfaces many people touch. Disinfect these daily:", textHi: "ऑफिस में कीटाणु उन सतहों से सबसे तेज़ फैलते हैं जिन्हें कई लोग छूते हैं। इन्हें रोज़ डिसइंफेक्ट करें:" },
      { type: "ul", items: [
        "Door handles, lift buttons and railings.",
        "Shared keyboards, mice and desk phones.",
        "Pantry counters, taps and the water dispenser.",
        "Meeting-room tables and chair arms.",
      ], itemsHi: [
        "दरवाज़ों के हैंडल, लिफ्ट के बटन और रेलिंग।",
        "साझा कीबोर्ड, माउस और डेस्क फोन।",
        "पैंट्री काउंटर, नल और वाटर डिस्पेंसर।",
        "मीटिंग-रूम की टेबल और कुर्सियों के हत्थे।",
      ]},
      { type: "h2", text: "A simple daily cleaning schedule", textHi: "एक आसान रोज़ाना सफाई शेड्यूल" },
      { type: "ol", items: [
        "Morning: wipe and disinfect all desks and shared surfaces before staff arrive.",
        "Midday: sanitize pantry and washroom touchpoints.",
        "Evening: empty bins, mop floors with a disinfectant cleaner and clean glass partitions.",
      ], itemsHi: [
        "सुबह: स्टाफ के आने से पहले सभी डेस्क और साझा सतहों को पोंछकर डिसइंफेक्ट करें।",
        "दोपहर: पैंट्री और वॉशरूम के टचपॉइंट्स सैनिटाइज़ करें।",
        "शाम: डस्टबिन खाली करें, डिसइंफेक्टेंट क्लीनर से फर्श पर पोछा लगाएँ और काँच के पार्टीशन साफ करें।",
      ]},
      { type: "h2", text: "Stock the essentials", textHi: "ज़रूरी चीज़ें स्टॉक में रखें" },
      { type: "p", text: "Keep sanitizer at the entrance and on every floor, hand wash at every washroom basin, and glass cleaner for the many glass surfaces modern offices have. A multi-purpose cleaner handles most other surfaces efficiently.", textHi: "एंट्रेंस पर और हर फ्लोर पर सैनिटाइज़र, हर वॉशरूम बेसिन पर हैंड वॉश, और आधुनिक ऑफिसों की ढेरों काँच की सतहों के लिए ग्लास क्लीनर रखें। बाकी ज़्यादातर सतहों के लिए मल्टी-परपज़ क्लीनर काफी है।" },
      { type: "quote", text: "Every rupee spent on workplace hygiene saves far more in reduced sick days and higher productivity.", textHi: "वर्कप्लेस हाइजीन पर खर्च किया हर रुपया बीमारी की छुट्टियाँ घटाकर और प्रोडक्टिविटी बढ़ाकर कहीं ज़्यादा बचत कराता है।" },
      { type: "p", text: "DPT Home Care supplies offices and corporates with reliable, bulk-quantity hygiene products — from sanitizers and hand wash to floor and glass cleaners — keeping your workplace spotless and your team protected.", textHi: "DPT Home Care ऑफिसों और कॉरपोरेट्स को भरोसेमंद, बल्क-क्वांटिटी हाइजीन प्रोडक्ट्स सप्लाई करता है — सैनिटाइज़र और हैंड वॉश से लेकर फ्लोर और ग्लास क्लीनर तक — ताकि आपका वर्कप्लेस बेदाग रहे और आपकी टीम सुरक्षित।" },
    ],
  },
  {
    slug: "daily-cleaning-checklist",
    title: "The Daily Cleaning Checklist Every Home Needs",
    titleHi: "रोज़ाना सफाई की चेकलिस्ट जो हर घर को चाहिए",
    excerpt:
      "Stop cleaning in exhausting weekend marathons. This simple daily checklist keeps your home consistently clean in just minutes a day.",
    excerptHi:
      "वीकेंड की थका देने वाली मैराथन सफाई बंद करें। यह आसान डेली चेकलिस्ट रोज़ बस कुछ मिनटों में आपके घर को लगातार साफ रखती है।",
    category: "Routine",
    categoryHi: "रूटीन",
    author: "DPT Home Care Team",
    date: "2025-04-28",
    readTime: "4 min read",
    readTimeHi: "4 मिनट",
    image: IMG.cozyHome,
    keywords: ["daily cleaning checklist", "cleaning routine", "house cleaning schedule", "home cleaning tips"],
    content: [
      { type: "p", text: "The secret to an always-tidy home isn't a heroic weekend clean — it's a handful of small daily habits. Spread across the day, these tasks take just minutes but keep your home consistently fresh and hygienic. Here's the checklist to follow.", textHi: "हमेशा साफ-सुथरे घर का राज़ वीकेंड की भारी-भरकम सफाई नहीं — बल्कि कुछ छोटी-छोटी रोज़ की आदतें हैं। दिन भर में बँटे ये काम बस कुछ मिनट लेते हैं, लेकिन आपके घर को लगातार तरोताज़ा और हाइजीनिक रखते हैं। यह रही अपनाने लायक चेकलिस्ट।" },
      { type: "h2", text: "Morning (10 minutes)", textHi: "सुबह (10 मिनट)" },
      { type: "ul", items: [
        "Make the beds and open the windows for fresh air.",
        "Wipe kitchen counters and the dining table.",
        "Quickly wipe the bathroom basin and mirror.",
      ], itemsHi: [
        "बिस्तर ठीक करें और ताज़ी हवा के लिए खिड़कियाँ खोलें।",
        "किचन काउंटर और डाइनिंग टेबल पोंछें।",
        "बाथरूम का बेसिन और शीशा झटपट पोंछ लें।",
      ]},
      { type: "h2", text: "Through the day (as you go)", textHi: "दिन भर (काम के साथ-साथ)" },
      { type: "ul", items: [
        "Wash utensils right after meals instead of piling them up.",
        "Wipe spills the moment they happen.",
        "Return items to their place to avoid clutter.",
      ], itemsHi: [
        "बर्तन जमा करने के बजाय खाने के तुरंत बाद धो लें।",
        "कुछ भी छलके तो उसी पल पोंछ दें।",
        "बिखराव से बचने के लिए चीज़ें वापस उनकी जगह पर रखें।",
      ]},
      { type: "h2", text: "Evening (15 minutes)", textHi: "शाम (15 मिनट)" },
      { type: "ul", items: [
        "Sweep or mop high-traffic floors with a disinfectant cleaner.",
        "Disinfect high-touch surfaces — handles, switches, phones.",
        "Empty the kitchen bin and rinse it.",
        "A couple of sprays of room freshener before you relax.",
      ], itemsHi: [
        "ज़्यादा आवाजाही वाले फर्श पर झाड़ू लगाएँ या डिसइंफेक्टेंट क्लीनर से पोछा लगाएँ।",
        "ज़्यादा छुई जाने वाली सतहें डिसइंफेक्ट करें — हैंडल, स्विच, फोन।",
        "किचन का डस्टबिन खाली करके धो लें।",
        "आराम करने से पहले रूम फ्रेशनर के दो-चार स्प्रे।",
      ]},
      { type: "quote", text: "Ten minutes a day beats three hours on Sunday — and your home stays guest-ready all week.", textHi: "रोज़ के दस मिनट रविवार के तीन घंटों पर भारी पड़ते हैं — और आपका घर पूरे हफ्ते मेहमानों के लिए तैयार रहता है।" },
      { type: "h2", text: "Keep the right tools within reach", textHi: "सही चीज़ें हाथ की पहुँच में रखें" },
      { type: "p", text: "The easier cleaning is, the more likely you'll keep it up. Keep a multi-purpose cleaner, a microfibre cloth and a hand wash in every key area. DPT Home Care's everyday range is designed to make this daily routine effortless and affordable.", textHi: "सफाई जितनी आसान होगी, उतनी ही नियमित रहेगी। हर ज़रूरी जगह पर एक मल्टी-परपज़ क्लीनर, माइक्रोफाइबर कपड़ा और हैंड वॉश रखें। DPT Home Care की एवरीडे रेंज इसी डेली रूटीन को आसान और किफायती बनाने के लिए बनी है।" },
    ],
  },
  {
    slug: "benefits-of-hand-wash",
    title: "Why Regular Hand Washing Matters: The Benefits of a Good Hand Wash",
    titleHi: "नियमित हाथ धोना क्यों ज़रूरी है: अच्छे हैंड वॉश के फायदे",
    excerpt:
      "Hand washing is the simplest, most powerful way to prevent illness. Discover why it matters and how to choose the right hand wash.",
    excerptHi:
      "हाथ धोना बीमारी से बचने का सबसे आसान, सबसे असरदार तरीका है। जानें यह क्यों मायने रखता है और सही हैंड वॉश कैसे चुनें।",
    category: "Personal Care",
    categoryHi: "पर्सनल केयर",
    author: "DPT Home Care Team",
    date: "2025-05-14",
    readTime: "5 min read",
    readTimeHi: "5 मिनट",
    image: IMG.handWash,
    keywords: ["benefits of hand wash", "hand washing", "hand hygiene", "germ protection"],
    content: [
      { type: "p", text: "It's the first thing we're taught as children and the advice health experts repeat most often: wash your hands. This simple habit is the single most effective way to stop the spread of germs and protect your family. Here's why it matters — and how to do it right.", textHi: "बचपन में हमें सबसे पहले यही सिखाया जाता है और स्वास्थ्य विशेषज्ञ भी सबसे ज़्यादा यही दोहराते हैं: हाथ धोइए। यह आसान आदत कीटाणुओं को फैलने से रोकने और परिवार की रक्षा करने का सबसे असरदार तरीका है। जानिए यह क्यों ज़रूरी है — और इसे सही तरीके से कैसे करें।" },
      { type: "h2", text: "Why hand washing is so effective", textHi: "हाथ धोना इतना असरदार क्यों है" },
      { type: "p", text: "Our hands touch hundreds of surfaces every day, picking up germs that then reach our eyes, nose and mouth — and our food. Washing with a good hand wash physically removes these germs before they can cause illness.", textHi: "हमारे हाथ रोज़ सैकड़ों सतहें छूते हैं और कीटाणु उठाते चलते हैं, जो फिर हमारी आँखों, नाक और मुँह — और हमारे खाने तक पहुँच जाते हैं। अच्छे हैंड वॉश से धोने पर ये कीटाणु बीमारी फैलाने से पहले ही हट जाते हैं।" },
      { type: "h2", text: "Key benefits of using a quality hand wash", textHi: "अच्छी क्वालिटी के हैंड वॉश के मुख्य फायदे" },
      { type: "ul", items: [
        "Removes germs, dirt and grease.",
        "Reduces the risk of common infections and stomach illness.",
        "Moisturising formulas keep skin soft, unlike harsh soaps.",
        "A pump dispenser is more hygienic than shared bar soap.",
        "A pleasant fragrance encourages the whole family to wash regularly.",
      ], itemsHi: [
        "कीटाणु, गंदगी और चिकनाई हटाता है।",
        "आम संक्रमण और पेट की बीमारियों का खतरा घटाता है।",
        "मॉइस्चराइज़िंग फॉर्मूला त्वचा को नरम रखता है, कठोर साबुनों की तरह नहीं।",
        "पंप डिस्पेंसर साझा साबुन की टिकिया से ज़्यादा हाइजीनिक होता है।",
        "अच्छी खुशबू पूरे परिवार को नियमित हाथ धोने के लिए प्रेरित करती है।",
      ]},
      { type: "h2", text: "When you should always wash your hands", textHi: "कब-कब हाथ ज़रूर धोने चाहिए" },
      { type: "ol", items: [
        "Before cooking, eating or handling food.",
        "After using the washroom.",
        "After returning home from outside.",
        "After coughing, sneezing or handling waste.",
      ], itemsHi: [
        "खाना बनाने, खाने या खाने की चीज़ें छूने से पहले।",
        "वॉशरूम इस्तेमाल करने के बाद।",
        "बाहर से घर लौटने के बाद।",
        "खाँसने, छींकने या कचरा छूने के बाद।",
      ]},
      { type: "h2", text: "Wash for at least 20 seconds", textHi: "कम से कम 20 सेकंड धोएँ" },
      { type: "p", text: "Lather all areas — palms, backs, between fingers and under nails — for at least 20 seconds before rinsing. When soap and water aren't available, use a 70% alcohol sanitizer as a backup.", textHi: "धोने से पहले कम से कम 20 सेकंड तक हर हिस्से पर झाग बनाएँ — हथेलियाँ, हाथों का पिछला हिस्सा, उँगलियों के बीच और नाखूनों के नीचे। जब साबुन-पानी उपलब्ध न हो, बैकअप के तौर पर 70% अल्कोहल वाला सैनिटाइज़र इस्तेमाल करें।" },
      { type: "quote", text: "Clean hands save lives. It's the cheapest, simplest health insurance your family can have.", textHi: "साफ हाथ ज़िंदगियाँ बचाते हैं। यह आपके परिवार का सबसे सस्ता, सबसे आसान हेल्थ इंश्योरेंस है।" },
      { type: "p", text: "DPT Hand Wash combines effective germ protection with skin-loving moisturisers, available in Rose, Lemon, Aloe Vera and Sea Breeze — so hand hygiene feels as good as it works.", textHi: "DPT Hand Wash असरदार जर्म प्रोटेक्शन के साथ त्वचा का ख्याल रखने वाले मॉइस्चराइज़र भी देता है — रोज़, लेमन, एलोवेरा और सी ब्रीज़ खुशबुओं में उपलब्ध — ताकि हाथों की हाइजीन जितनी असरदार हो, महसूस भी उतनी ही अच्छी हो।" },
    ],
  },
  {
    slug: "importance-of-toilet-cleaner",
    title: "The Importance of Using a Good Toilet Cleaner",
    titleHi: "अच्छे टॉयलेट क्लीनर का इस्तेमाल क्यों ज़रूरी है",
    excerpt:
      "The toilet is the most germ-dense spot in your home. Learn why a quality toilet cleaner is essential and how to use it effectively.",
    excerptHi:
      "टॉयलेट घर की सबसे ज़्यादा कीटाणुओं वाली जगह है। जानें कि अच्छा टॉयलेट क्लीनर क्यों ज़रूरी है और इसका असरदार इस्तेमाल कैसे करें।",
    category: "Bathroom",
    categoryHi: "बाथरूम",
    author: "DPT Home Care Team",
    date: "2025-05-30",
    readTime: "5 min read",
    readTimeHi: "5 मिनट",
    image: IMG.toiletBowl,
    keywords: ["toilet cleaner", "importance of toilet cleaner", "toilet hygiene", "germ free toilet"],
    content: [
      { type: "p", text: "It's not the most glamorous topic, but it's one of the most important. The toilet harbours more germs than almost anywhere else in your home, and a regular household cleaner simply isn't enough. Here's why a dedicated toilet cleaner is essential for a healthy home.", textHi: "यह कोई बहुत आकर्षक विषय नहीं है, पर सबसे ज़रूरी विषयों में से एक ज़रूर है। टॉयलेट में घर की लगभग किसी भी और जगह से ज़्यादा कीटाणु पलते हैं, और आम घरेलू क्लीनर यहाँ काफी नहीं होता। जानिए स्वस्थ घर के लिए एक खास टॉयलेट क्लीनर क्यों ज़रूरी है।" },
      { type: "h2", text: "What's really lurking in your toilet", textHi: "आपके टॉयलेट में असल में क्या छिपा है" },
      { type: "p", text: "Toilets can harbour bacteria that cause serious stomach and intestinal infections. These germs can spread to hands and surfaces, especially around the seat, rim and flush button. A specialised toilet cleaner is formulated to destroy them.", textHi: "टॉयलेट में ऐसे बैक्टीरिया पल सकते हैं जो पेट और आँतों के गंभीर संक्रमण फैलाते हैं। ये कीटाणु हाथों और सतहों तक फैल सकते हैं, खासकर सीट, रिम और फ्लश बटन के आसपास। स्पेशलाइज़्ड टॉयलेट क्लीनर इन्हीं को खत्म करने के लिए बनाया जाता है।" },
      { type: "h2", text: "Why an ordinary cleaner isn't enough", textHi: "आम क्लीनर काफी क्यों नहीं है" },
      { type: "ul", items: [
        "Toilet cleaners are thicker, so they cling and stay in contact longer.",
        "Their acidic formula dissolves limescale, rust and yellow stains.",
        "They are specifically designed to kill toilet germs.",
        "They neutralise the bacteria that cause persistent odour.",
      ], itemsHi: [
        "टॉयलेट क्लीनर गाढ़े होते हैं, इसलिए सतह पर चिपककर देर तक असर करते हैं।",
        "इनका एसिडिक फॉर्मूला लाइमस्केल, जंग और पीले दाग घोल देता है।",
        "ये खासतौर पर टॉयलेट के कीटाणु मारने के लिए बनाए जाते हैं।",
        "ये लगातार बदबू पैदा करने वाले बैक्टीरिया को बेअसर कर देते हैं।",
      ]},
      { type: "h2", text: "How to use a toilet cleaner correctly", textHi: "टॉयलेट क्लीनर का सही इस्तेमाल कैसे करें" },
      { type: "ol", items: [
        "Squeeze the cleaner around and under the rim so it coats the inner bowl.",
        "Leave it for 5–10 minutes (longer for stubborn stains).",
        "Scrub thoroughly with a toilet brush, reaching under the rim.",
        "Flush to rinse and reveal a sparkling, hygienic bowl.",
      ], itemsHi: [
        "क्लीनर को रिम के चारों ओर और नीचे डालें ताकि वह पूरे अंदरूनी बाउल पर फैल जाए।",
        "5–10 मिनट लगा रहने दें (ज़िद्दी दागों के लिए और ज़्यादा)।",
        "टॉयलेट ब्रश से अच्छी तरह रगड़ें, रिम के नीचे तक पहुँचते हुए।",
        "फ्लश करें — और पाएँ चमकदार, हाइजीनिक बाउल।",
      ]},
      { type: "quote", text: "A visibly clean toilet and a hygienic toilet are two different things — only a proper cleaner delivers both.", textHi: "दिखने में साफ टॉयलेट और हाइजीनिक टॉयलेट दो अलग चीज़ें हैं — दोनों सिर्फ एक सही क्लीनर ही दे सकता है।" },
      { type: "p", text: "DPT Toilet Cleaner is a thick, clinging formula that dissolves the toughest stains, kills germs and leaves a fresh pine fragrance. Use it two to three times a week for a consistently hygienic washroom.", textHi: "DPT Toilet Cleaner एक गाढ़ा, सतह पर चिपकने वाला फॉर्मूला है जो सबसे ज़िद्दी दाग घोलता है, कीटाणु मारता है और ताज़ा पाइन खुशबू छोड़ता है। लगातार हाइजीनिक वॉशरूम के लिए इसे हफ्ते में दो-तीन बार इस्तेमाल करें।" },
    ],
  },
  {
    slug: "how-to-keep-home-fresh",
    title: "How to Keep Your Home Smelling Fresh All Day",
    titleHi: "अपने घर को दिन भर महकता कैसे रखें",
    excerpt:
      "A fresh-smelling home feels clean and welcoming. Learn how to eliminate odours at the source and keep every room smelling wonderful.",
    excerptHi:
      "महकता घर साफ और स्वागत करता हुआ महसूस होता है। जानें बदबू को जड़ से कैसे खत्म करें और हर कमरे को खुशबूदार कैसे रखें।",
    category: "Fresh Home",
    categoryHi: "फ्रेश होम",
    author: "DPT Home Care Team",
    date: "2025-06-15",
    readTime: "5 min read",
    readTimeHi: "5 मिनट",
    image: IMG.homePlants,
    keywords: ["keep home fresh", "home fragrance", "room freshener", "remove household odours"],
    content: [
      { type: "p", text: "Have you ever walked into a home that instantly felt clean and welcoming? Often it's not what you see — it's what you smell. A fresh-smelling home lifts the mood and signals cleanliness. Here's how to achieve lasting freshness in every room.", textHi: "क्या आप कभी किसी ऐसे घर में गए हैं जो घुसते ही साफ और अपनापन भरा लगा? अक्सर वह वो नहीं होता जो आप देखते हैं — बल्कि वो होता है जो आप सूँघते हैं। महकता घर मूड अच्छा करता है और सफाई का एहसास देता है। जानिए हर कमरे में देर तक टिकने वाली ताज़गी कैसे पाएँ।" },
      { type: "h2", text: "Eliminate odours at the source", textHi: "बदबू को जड़ से खत्म करें" },
      { type: "p", text: "Fragrance masks smells, but true freshness starts with removing the source. Tackle these common culprits first:", textHi: "खुशबू बदबू को ढकती है, लेकिन असली ताज़गी उसकी जड़ हटाने से शुरू होती है। पहले इन आम कारणों से निपटें:" },
      { type: "ul", items: [
        "Empty and rinse kitchen bins daily.",
        "Clean the sink and drains, where food residue causes smells.",
        "Wash damp cloths, mats and towels regularly.",
        "Keep the bathroom clean and well-ventilated.",
      ], itemsHi: [
        "किचन का डस्टबिन रोज़ खाली करके धोएँ।",
        "सिंक और नालियाँ साफ करें, जहाँ खाने के अवशेष बदबू पैदा करते हैं।",
        "गीले कपड़े, मैट और तौलिये नियमित धोएँ।",
        "बाथरूम को साफ और हवादार रखें।",
      ]},
      { type: "h2", text: "Let fresh air circulate", textHi: "ताज़ी हवा आने दें" },
      { type: "p", text: "Open windows for at least 15 minutes a day to clear stale air and moisture. Good ventilation is the free, natural foundation of a fresh home.", textHi: "बासी हवा और नमी निकालने के लिए रोज़ कम से कम 15 मिनट खिड़कियाँ खोलें। अच्छा वेंटिलेशन तरोताज़ा घर की मुफ्त, कुदरती बुनियाद है।" },
      { type: "h2", text: "Layer in a lasting fragrance", textHi: "देर तक टिकने वाली खुशबू की परतें जोड़ें" },
      { type: "p", text: "Once the source is handled, add fragrance for that welcoming touch. A quality room freshener neutralises odour molecules rather than just covering them, leaving a clean scent that lingers.", textHi: "जब जड़ का इलाज हो जाए, तो उस स्वागत भरे एहसास के लिए खुशबू जोड़ें। अच्छी क्वालिटी का रूम फ्रेशनर बदबू के कणों को सिर्फ ढकने के बजाय बेअसर करता है, और पीछे छोड़ जाता है देर तक टिकने वाली साफ महक।" },
      { type: "ol", items: [
        "Spray a room freshener in living areas each morning.",
        "Use fabric conditioner so clothes and linens smell fresh for days.",
        "Mop floors with a fragranced floor cleaner for whole-room freshness.",
      ], itemsHi: [
        "हर सुबह लिविंग एरिया में रूम फ्रेशनर स्प्रे करें।",
        "फैब्रिक कंडीशनर इस्तेमाल करें ताकि कपड़े और चादरें कई दिनों तक महकें।",
        "खुशबूदार फ्लोर क्लीनर से पोछा लगाएँ ताकि पूरा कमरा महक उठे।",
      ]},
      { type: "quote", text: "Freshness isn't about the strongest fragrance — it's about a clean base scent that makes your whole home feel cared for.", textHi: "ताज़गी सबसे तेज़ खुशबू का नाम नहीं — बल्कि उस साफ बुनियादी महक का नाम है जो पूरे घर को सहेजा हुआ महसूस कराती है।" },
      { type: "p", text: "DPT's Room Freshener range — Lavender, Citrus Bloom, Rose and Ocean — plus our fragranced floor cleaners and fabric conditioner, help you build lasting, layered freshness throughout your home.", textHi: "DPT की रूम फ्रेशनर रेंज — लैवेंडर, सिट्रस ब्लूम, रोज़ और ओशन — और हमारे खुशबूदार फ्लोर क्लीनर व फैब्रिक कंडीशनर मिलकर आपके पूरे घर में देर तक टिकने वाली, परत-दर-परत ताज़गी बनाते हैं।" },
    ],
  },
  {
    slug: "cleaning-during-monsoon",
    title: "Monsoon Cleaning Guide: Keep Your Home Hygienic in the Rains",
    titleHi: "मानसून क्लीनिंग गाइड: बारिश में घर को हाइजीनिक रखें",
    excerpt:
      "The monsoon brings dampness, mud and germs. This seasonal guide helps you keep your home clean, dry and healthy through the rainy season.",
    excerptHi:
      "मानसून अपने साथ नमी, कीचड़ और कीटाणु लाता है। यह सीज़नल गाइड बारिश के पूरे मौसम में आपके घर को साफ, सूखा और स्वस्थ रखने में मदद करेगी।",
    category: "Seasonal",
    categoryHi: "सीज़नल",
    author: "DPT Home Care Team",
    date: "2025-06-28",
    readTime: "6 min read",
    readTimeHi: "6 मिनट",
    image: IMG.moppingBeige,
    keywords: ["monsoon cleaning", "rainy season cleaning", "prevent mould", "monsoon hygiene"],
    content: [
      { type: "p", text: "The monsoon is a welcome relief from the heat, but it brings its own hygiene challenges — muddy floors, damp corners, musty smells and a spike in germs and insects. With the right approach, you can keep your home clean, dry and healthy all season long.", textHi: "मानसून गर्मी से राहत तो देता है, पर अपने साथ हाइजीन की चुनौतियाँ भी लाता है — कीचड़ भरे फर्श, सीलन भरे कोने, बासी सी बदबू और कीटाणुओं व कीड़ों की बढ़त। सही तरीका अपनाएँ तो आप पूरे मौसम अपने घर को साफ, सूखा और स्वस्थ रख सकते हैं।" },
      { type: "h2", text: "Tackle mud and moisture at the entrance", textHi: "कीचड़ और नमी को दरवाज़े पर ही रोकें" },
      { type: "ul", items: [
        "Place absorbent mats at every doorway and clean them often.",
        "Mop entrance floors daily with a disinfectant floor cleaner.",
        "Keep a dedicated cloth to wipe muddy footprints quickly.",
      ], itemsHi: [
        "हर दरवाज़े पर पानी सोखने वाले मैट रखें और उन्हें अक्सर साफ करें।",
        "एंट्रेंस के फर्श पर रोज़ डिसइंफेक्टेंट फ्लोर क्लीनर से पोछा लगाएँ।",
        "कीचड़ भरे पैरों के निशान झट से पोंछने के लिए एक अलग कपड़ा रखें।",
      ]},
      { type: "h2", text: "Prevent mould and musty smells", textHi: "फफूंदी और सीलन की बदबू से बचाव करें" },
      { type: "p", text: "Dampness encourages mould and bacteria. Fight back by keeping surfaces dry and disinfected:", textHi: "नमी फफूंदी और बैक्टीरिया को बढ़ावा देती है। सतहों को सूखा और डिसइंफेक्टेड रखकर मुकाबला करें:" },
      { type: "ol", items: [
        "Wipe damp walls and window sills regularly.",
        "Clean bathroom tiles and grout with a bathroom cleaner to stop mould.",
        "Use a room freshener to counter the musty monsoon smell.",
        "Let in sunlight and air whenever the rain pauses.",
      ], itemsHi: [
        "सीलन वाली दीवारें और खिड़कियों की सिलें नियमित पोंछें।",
        "फफूंदी रोकने के लिए बाथरूम की टाइल्स और ग्राउट को बाथरूम क्लीनर से साफ करें।",
        "मानसून की सीलन भरी बदबू से निपटने के लिए रूम फ्रेशनर इस्तेमाल करें।",
        "जब भी बारिश थमे, धूप और हवा अंदर आने दें।",
      ]},
      { type: "h2", text: "Step up disinfection", textHi: "डिसइंफेक्शन बढ़ा दें" },
      { type: "p", text: "Germs and infections rise during the monsoon. Increase how often you disinfect floors and high-touch surfaces, and keep hand wash and sanitizer readily available for the whole family.", textHi: "मानसून में कीटाणु और संक्रमण बढ़ जाते हैं। फर्श और ज़्यादा छुई जाने वाली सतहों को पहले से ज़्यादा बार डिसइंफेक्ट करें, और पूरे परिवार के लिए हैंड वॉश और सैनिटाइज़र हमेशा हाथ के पास रखें।" },
      { type: "h2", text: "Protect against insects", textHi: "कीड़ों से बचाव करें" },
      { type: "p", text: "Standing water and food residue attract insects. Clean drains with phenyl, keep the kitchen spotless, and avoid leaving damp cloths around.", textHi: "रुका हुआ पानी और खाने के अवशेष कीड़ों को खींचते हैं। नालियों को फिनाइल से साफ करें, किचन को बेदाग रखें, और गीले कपड़े इधर-उधर न छोड़ें।" },
      { type: "quote", text: "In the monsoon, dryness is hygiene. A dry, disinfected surface gives germs and mould nowhere to grow.", textHi: "मानसून में सूखापन ही हाइजीन है। सूखी, डिसइंफेक्टेड सतह पर कीटाणुओं और फफूंदी को पनपने की जगह ही नहीं मिलती।" },
      { type: "p", text: "DPT Home Care's disinfectant floor cleaner, phenyl, bathroom cleaner and room fresheners give you everything you need to keep your home hygienic and fresh right through the rainy season.", textHi: "DPT Home Care का डिसइंफेक्टेंट फ्लोर क्लीनर, फिनाइल, बाथरूम क्लीनर और रूम फ्रेशनर — बारिश के पूरे मौसम में घर को हाइजीनिक और तरोताज़ा रखने के लिए जो चाहिए, वह सब आपको दे देते हैं।" },
    ],
  },
  {
    slug: "best-household-cleaning-products",
    title: "Best Household Cleaning Products Every Indian Home Needs",
    titleHi: "हर भारतीय घर के लिए ज़रूरी बेहतरीन क्लीनिंग प्रोडक्ट्स",
    excerpt:
      "Overwhelmed by cleaning product choices? Here are the essential cleaners every home needs — and how to use each one effectively.",
    excerptHi:
      "क्लीनिंग प्रोडक्ट्स के ढेरों विकल्पों में उलझ गए हैं? ये हैं हर घर के लिए ज़रूरी क्लीनर — और हर एक का असरदार इस्तेमाल कैसे करें।",
    category: "Buying Guide",
    categoryHi: "बाइंग गाइड",
    author: "DPT Home Care Team",
    date: "2025-07-18",
    readTime: "7 min read",
    readTimeHi: "7 मिनट",
    image: IMG.cleaningProducts,
    keywords: ["best household cleaning products", "cleaning products list", "home cleaning essentials", "cleaning supplies india"],
    content: [
      { type: "p", text: "Walk down any cleaning aisle and the choices are overwhelming. But you don't need dozens of products — just the right essentials, each doing its job well. Here's the definitive list of cleaning products every Indian home needs, and how to get the most from each.", textHi: "किसी भी दुकान के क्लीनिंग सेक्शन में जाइए और विकल्पों की भरमार चकरा देती है। लेकिन आपको दर्जनों प्रोडक्ट्स नहीं चाहिए — बस सही ज़रूरी चीज़ें, जिनमें हर एक अपना काम बखूबी करे। पेश है हर भारतीय घर के लिए ज़रूरी क्लीनिंग प्रोडक्ट्स की पक्की लिस्ट, और हर एक से पूरा फायदा उठाने का तरीका।" },
      { type: "h2", text: "The 8 essentials for every home", textHi: "हर घर के लिए 8 ज़रूरी चीज़ें" },
      { type: "ol", items: [
        "Floor Cleaner — for daily disinfected, fragrant floors across the whole house.",
        "Toilet Cleaner — a thick, germ-killing formula for a hygienic washroom.",
        "Bathroom Cleaner — removes soap scum and hard-water marks from tiles and fittings.",
        "Dish Wash Liquid — cuts kitchen grease and keeps utensils shining.",
        "Glass Cleaner — for streak-free mirrors, windows and glass surfaces.",
        "Hand Wash — germ protection with moisturising care at every basin.",
        "Multi-Purpose Cleaner — one versatile cleaner for many surfaces.",
        "Room Freshener — the finishing touch for a welcoming home.",
      ], itemsHi: [
        "Floor Cleaner — पूरे घर के फर्श रोज़ डिसइंफेक्टेड और खुशबूदार रखने के लिए।",
        "Toilet Cleaner — हाइजीनिक वॉशरूम के लिए गाढ़ा, कीटाणु मारने वाला फॉर्मूला।",
        "Bathroom Cleaner — टाइल्स और फिटिंग्स से साबुन की परत और हार्ड-वाटर के निशान हटाता है।",
        "Dish Wash Liquid — किचन की चिकनाई काटता है और बर्तनों को चमकाता है।",
        "Glass Cleaner — शीशों, खिड़कियों और काँच की सतहों की बेदाग चमक के लिए।",
        "Hand Wash — हर बेसिन पर जर्म प्रोटेक्शन के साथ मॉइस्चराइज़िंग केयर।",
        "Multi-Purpose Cleaner — कई सतहों के लिए एक ही बहुमुखी क्लीनर।",
        "Room Freshener — स्वागत करते घर का फिनिशिंग टच।",
      ]},
      { type: "h2", text: "Nice-to-have extras", textHi: "हों तो और भी अच्छा" },
      { type: "ul", items: [
        "Liquid Detergent and Fabric Conditioner for laundry day.",
        "Kitchen Cleaner for heavy grease and chimney cleaning.",
        "Sanitizer for on-the-go hand hygiene.",
        "Car Shampoo for a weekend vehicle wash.",
      ], itemsHi: [
        "लॉन्ड्री के दिन के लिए Liquid Detergent और Fabric Conditioner।",
        "भारी चिकनाई और चिमनी की सफाई के लिए Kitchen Cleaner।",
        "चलते-फिरते हाथों की हाइजीन के लिए Sanitizer।",
        "वीकेंड पर गाड़ी धोने के लिए Car Shampoo।",
      ]},
      { type: "h2", text: "How to choose quality over hype", textHi: "दिखावे की जगह क्वालिटी कैसे चुनें" },
      { type: "p", text: "Look for concentrated formulas (more washes per bottle), genuine disinfectant action, and trusted manufacturing. A slightly higher-quality product almost always works out cheaper per use because you need less of it.", textHi: "कॉन्सेंट्रेटेड फॉर्मूला (हर बोतल में ज़्यादा धुलाई), असली डिसइंफेक्टेंट असर और भरोसेमंद मैन्युफैक्चरिंग देखें। थोड़ा बेहतर क्वालिटी का प्रोडक्ट लगभग हमेशा हर इस्तेमाल पर सस्ता पड़ता है, क्योंकि उसकी ज़रूरत कम मात्रा में होती है।" },
      { type: "quote", text: "You don't need a cupboard full of products — you need a handful of really good ones.", textHi: "आपको प्रोडक्ट्स से भरी अलमारी नहीं चाहिए — चाहिए बस कुछ सचमुच अच्छे प्रोडक्ट्स।" },
      { type: "h2", text: "One brand, complete coverage", textHi: "एक ब्रांड, पूरी कवरेज" },
      { type: "p", text: "DPT Home Care manufactures all these essentials — 15 products covering floor, bathroom, kitchen, fabric, personal and air care. Buying a complete range from one trusted manufacturer means consistent quality, better value and simpler restocking. That's the Power of Hygiene, made simple.", textHi: "DPT Home Care ये सभी ज़रूरी प्रोडक्ट्स खुद बनाता है — फ्लोर, बाथरूम, किचन, फैब्रिक, पर्सनल और एयर केयर को कवर करते 15 प्रोडक्ट्स। एक भरोसेमंद मैन्युफैक्चरर से पूरी रेंज खरीदने का मतलब है एक जैसी क्वालिटी, बेहतर वैल्यू और आसान रीस्टॉकिंग। यही है Power of Hygiene, आसान बनाई हुई।" },
    ],
  },
];

export function getPost(slug: string): BlogPost | undefined {
  return blogPosts.find((p) => p.slug === slug);
}

export function getRelatedPosts(slug: string, limit = 3): BlogPost[] {
  const current = getPost(slug);
  const others = blogPosts.filter((p) => p.slug !== slug);
  if (!current) return others.slice(0, limit);
  const sameCat = others.filter((p) => p.category === current.category);
  const rest = others.filter((p) => p.category !== current.category);
  return [...sameCat, ...rest].slice(0, limit);
}
