import { IMG } from "./images";
import type { BlogPost } from "./types";

export const blogPosts: BlogPost[] = [
  {
    slug: "how-to-clean-bathroom",
    title: "How to Clean Your Bathroom: A Step-by-Step Guide",
    excerpt:
      "A clean bathroom is the heart of a hygienic home. Follow this simple, room-by-room routine to keep every surface sparkling and germ-free.",
    category: "Bathroom",
    author: "DPT Home Care Team",
    date: "2025-01-12",
    readTime: "6 min read",
    image: IMG.bathroomTiles,
    keywords: ["how to clean bathroom", "bathroom cleaning guide", "toilet cleaning", "bathroom hygiene"],
    content: [
      { type: "p", text: "The bathroom is one of the most used — and most germ-prone — rooms in any home. Soap scum, hard-water stains and bacteria build up quickly, but with the right products and a simple routine, you can keep it spotless in under 20 minutes. Here's exactly how the professionals do it." },
      { type: "h2", text: "Start from the top, work downwards" },
      { type: "p", text: "Always clean from the highest point to the lowest so that dust and drips fall onto areas you haven't cleaned yet. Begin with mirrors and shelves, move to tiles and fittings, then finish with the toilet and floor." },
      { type: "h2", text: "Step-by-step bathroom cleaning routine" },
      { type: "ol", items: [
        "Clear the space: remove bottles, mats and bins so every surface is accessible.",
        "Spray the mirror with DPT Glass Cleaner and wipe with a dry microfibre cloth for a streak-free shine.",
        "Apply DPT Bathroom Cleaner to tiles, the wash basin, taps and shower. Leave it for 2–3 minutes to dissolve soap scum.",
        "Scrub gently and rinse to reveal the original shine of your fittings.",
        "Apply DPT Toilet Cleaner around and under the rim, leave for 5–10 minutes, then scrub and flush.",
        "Finally, mop the floor with diluted DPT Floor Cleaner for a disinfected, fragrant finish.",
      ]},
      { type: "h2", text: "Don't forget these hidden germ hotspots" },
      { type: "ul", items: [
        "Taps and handles — touched constantly, cleaned rarely.",
        "The underside of the toilet seat and the flush button.",
        "Shower drains, where hair and residue collect.",
        "The gap between tiles, where grime and mould hide.",
      ]},
      { type: "quote", text: "A bathroom that looks clean isn't always hygienic. Disinfecting the surfaces you touch most is what truly protects your family." },
      { type: "h2", text: "How often should you clean?" },
      { type: "p", text: "Wipe surfaces and the mirror daily, do a full clean twice a week, and deep-clean grout and drains once a month. Consistency beats intensity — a quick daily wipe keeps the weekly clean effortless." },
      { type: "p", text: "With DPT Home Care's complete bathroom range — glass cleaner, bathroom cleaner and toilet cleaner — you have everything you need for a spotless, germ-free washroom that stays fresh for longer." },
    ],
  },
  {
    slug: "best-floor-cleaner",
    title: "How to Choose the Best Floor Cleaner for Your Home",
    excerpt:
      "Not all floor cleaners are equal. Learn how to pick the right one for your flooring type and get a spotless, disinfected, long-lasting shine.",
    category: "Floor Care",
    author: "DPT Home Care Team",
    date: "2025-02-04",
    readTime: "5 min read",
    image: IMG.tiledFloor,
    keywords: ["best floor cleaner", "floor cleaner for tiles", "marble floor cleaner", "disinfectant floor cleaner"],
    content: [
      { type: "p", text: "Your floor is the largest surface in your home and the first thing guests notice. The right floor cleaner does three jobs at once: it removes dirt, kills germs and leaves a lasting fragrance — without damaging your flooring. Here's how to choose wisely." },
      { type: "h2", text: "Match the cleaner to your floor type" },
      { type: "ul", items: [
        "Marble & granite: use a pH-balanced, non-acidic cleaner to protect the natural stone.",
        "Ceramic & vitrified tiles: almost any quality cleaner works; look for streak-free formulas.",
        "Wooden floors: use a heavily diluted solution and a well-wrung mop to avoid water damage.",
      ]},
      { type: "h2", text: "Look for these key qualities" },
      { type: "ol", items: [
        "Strong disinfectant action against germs.",
        "A concentrated formula, so you use less per bucket and save money.",
        "A no-rinse, no-residue finish that dries without stickiness.",
        "A long-lasting fragrance that keeps rooms fresh for hours.",
      ]},
      { type: "h2", text: "Why concentration matters" },
      { type: "p", text: "A concentrated cleaner like DPT Floor Cleaner needs only one capful per bucket of water. That means a single bottle lasts far longer than diluted supermarket brands — better cleaning at a lower cost per wash." },
      { type: "quote", text: "The best floor cleaner isn't the cheapest bottle — it's the one that gives you the most clean, germ-free washes for your money." },
      { type: "h2", text: "Our recommendation" },
      { type: "p", text: "DPT Floor Cleaner is safe on marble, granite, tiles and vitrified floors, disinfects as it cleans, and comes in Floral, Citrus, Jasmine and Lavender fragrances. For institutions and large areas, our concentrated Phenyl offers powerful, economical disinfection." },
    ],
  },
  {
    slug: "kitchen-cleaning-tips",
    title: "10 Kitchen Cleaning Tips for a Spotless, Hygienic Kitchen",
    excerpt:
      "Grease, food stains and clutter make the kitchen the hardest room to clean. These 10 practical tips keep yours hygienic and shining every day.",
    category: "Kitchen",
    author: "DPT Home Care Team",
    date: "2025-02-20",
    readTime: "6 min read",
    image: IMG.kitchenSurface,
    keywords: ["kitchen cleaning tips", "how to clean kitchen", "degreaser", "kitchen hygiene"],
    content: [
      { type: "p", text: "The kitchen is where hygiene matters most — it's where your family's food is prepared. Yet grease, spills and food residue make it the toughest room to keep clean. These ten expert tips will help you maintain a spotless, food-safe kitchen with minimal effort." },
      { type: "h2", text: "Daily habits that keep grease away" },
      { type: "ol", items: [
        "Wipe the countertop and stove after every meal, while spills are still fresh and easy to remove.",
        "Wash utensils immediately with DPT Dish Wash Liquid to stop grease from hardening.",
        "Clean the sink daily — it holds more bacteria than most people realise.",
        "Empty and rinse the dustbin every night to prevent odour and pests.",
        "Keep a spray bottle of DPT Kitchen Cleaner handy for instant degreasing.",
      ]},
      { type: "h2", text: "Weekly deep-cleaning tasks" },
      { type: "ol", items: [
        "Degrease the chimney and exhaust filter, where oil builds up fastest.",
        "Wipe down cabinet fronts and handles, common touchpoints for grease and germs.",
        "Clean the tiles behind the stove with a degreaser to remove oil splatter.",
        "Disinfect the fridge handles and shelves.",
        "Mop the floor with a disinfectant floor cleaner to finish.",
      ]},
      { type: "h2", text: "The secret to cutting through grease" },
      { type: "p", text: "Baked-on grease needs contact time. Spray DPT Kitchen Cleaner, wait one to two minutes, then wipe — no hard scrubbing required. For utensils, a lemon-based dish wash liquid dissolves oil far faster than plain soap." },
      { type: "quote", text: "A clean kitchen isn't about scrubbing harder — it's about cleaning smarter, and cleaning little and often." },
      { type: "p", text: "Always rinse food-contact surfaces with clean water after using any cleaner. With DPT's kitchen range, you get powerful degreasing that keeps your kitchen hygienic and shining." },
    ],
  },
  {
    slug: "home-hygiene-guide",
    title: "The Complete Home Hygiene Guide for a Healthier Family",
    excerpt:
      "Home hygiene is your family's first line of defence against illness. This complete guide covers every room and every essential habit.",
    category: "Hygiene",
    author: "DPT Home Care Team",
    date: "2025-03-08",
    readTime: "7 min read",
    image: IMG.family,
    keywords: ["home hygiene", "household hygiene guide", "healthy home", "germ protection"],
    content: [
      { type: "p", text: "A hygienic home is a healthy home. Germs spread through the surfaces we touch, the air we breathe and the hands we shake. This complete guide walks you through building a hygiene routine that protects everyone under your roof — without turning cleaning into a full-time job." },
      { type: "h2", text: "Focus on high-touch surfaces" },
      { type: "p", text: "Most germs spread through frequently touched surfaces. Disinfect these daily, especially during flu season:" },
      { type: "ul", items: [
        "Door handles, switches and remote controls.",
        "Taps, flush buttons and toilet seats.",
        "Dining tables and kitchen counters.",
        "Mobile phones and children's toys.",
      ]},
      { type: "h2", text: "Room-by-room hygiene essentials" },
      { type: "h3", text: "Kitchen" },
      { type: "p", text: "Wash utensils promptly, degrease surfaces and disinfect the sink daily. Food hygiene starts with a clean kitchen." },
      { type: "h3", text: "Bathroom" },
      { type: "p", text: "Use a disinfectant toilet cleaner and bathroom cleaner regularly, and keep a fresh hand wash at every basin." },
      { type: "h3", text: "Living areas" },
      { type: "p", text: "Dust and mop floors with a disinfectant cleaner, and keep the air fresh with a quality room freshener." },
      { type: "h2", text: "Hand hygiene is non-negotiable" },
      { type: "p", text: "Hand washing remains the single most effective way to prevent the spread of infection. Keep a moisturising hand wash at every sink and a sanitizer near the entrance for when soap and water aren't available." },
      { type: "quote", text: "You can't see germs — which is exactly why a consistent hygiene routine matters more than an occasional deep clean." },
      { type: "h2", text: "Build a simple, repeatable routine" },
      { type: "p", text: "The goal isn't perfection; it's consistency. A few daily habits — wiping surfaces, washing hands and keeping rooms fresh — protect your family far better than one big monthly clean. DPT Home Care's complete range makes building that routine simple and affordable." },
    ],
  },
  {
    slug: "how-to-remove-tough-stains",
    title: "How to Remove Tough Stains: The Ultimate Guide",
    excerpt:
      "From oil and ink to hard-water marks and rust, this guide shows you how to tackle the most stubborn stains around your home.",
    category: "Stain Removal",
    author: "DPT Home Care Team",
    date: "2025-03-25",
    readTime: "6 min read",
    image: "/brand/blog-stain-removal.jpg",
    keywords: ["how to remove tough stains", "stain removal", "hard water stains", "grease stain remover"],
    content: [
      { type: "p", text: "Every home battles stubborn stains — grease on the stove, hard-water marks in the bathroom, ink on the sofa. The key to winning is knowing which product to use and giving it enough contact time. Here's your room-by-room stain-removal playbook." },
      { type: "h2", text: "The golden rule: act fast" },
      { type: "p", text: "Fresh stains are always easier to remove than dried ones. Blot spills immediately (don't rub, which spreads them) and treat them before they set." },
      { type: "h2", text: "Common stains and how to beat them" },
      { type: "h3", text: "Grease and oil" },
      { type: "p", text: "Spray a degreasing kitchen cleaner, wait two minutes, then wipe. For fabric, apply a little dish wash liquid to the spot before washing." },
      { type: "h3", text: "Hard-water and limescale marks" },
      { type: "p", text: "These white, chalky deposits respond to an acidic bathroom or toilet cleaner. Apply, leave for a few minutes, then scrub gently." },
      { type: "h3", text: "Rust and yellow toilet stains" },
      { type: "p", text: "A thick toilet cleaner that clings to the surface works best. Leave it on for 10–15 minutes before scrubbing." },
      { type: "h3", text: "Fabric stains" },
      { type: "p", text: "Pre-soak in a liquid detergent solution, then wash. Liquid detergent penetrates fibres better than powder and leaves no residue." },
      { type: "ul", items: [
        "Always test on a small hidden area first.",
        "Never mix different cleaning chemicals together.",
        "Give the product time to work — patience beats scrubbing.",
        "Rinse thoroughly after treating any stain.",
      ]},
      { type: "quote", text: "The right cleaner and a little patience will remove almost any stain — harsh scrubbing usually just damages the surface." },
      { type: "p", text: "With DPT Home Care's specialised range, you have the right formula for every kind of stain, from kitchen grease to bathroom limescale." },
    ],
  },
  {
    slug: "office-cleaning-tips",
    title: "Office Cleaning Tips for a Healthier, More Productive Workplace",
    excerpt:
      "A clean office reduces sick days and boosts productivity. Use these practical tips to keep your workplace hygienic and professional.",
    category: "Office",
    author: "DPT Home Care Team",
    date: "2025-04-10",
    readTime: "5 min read",
    image: IMG.ppeDisinfect,
    keywords: ["office cleaning tips", "workplace hygiene", "commercial cleaning", "office sanitization"],
    content: [
      { type: "p", text: "A clean workplace does more than look professional — it directly affects employee health, morale and productivity. Shared desks, keyboards and door handles are germ highways. Here's how to keep your office hygienic and your team healthy." },
      { type: "h2", text: "Prioritise shared touchpoints" },
      { type: "p", text: "In an office, germs spread fastest through surfaces many people touch. Disinfect these daily:" },
      { type: "ul", items: [
        "Door handles, lift buttons and railings.",
        "Shared keyboards, mice and desk phones.",
        "Pantry counters, taps and the water dispenser.",
        "Meeting-room tables and chair arms.",
      ]},
      { type: "h2", text: "A simple daily cleaning schedule" },
      { type: "ol", items: [
        "Morning: wipe and disinfect all desks and shared surfaces before staff arrive.",
        "Midday: sanitize pantry and washroom touchpoints.",
        "Evening: empty bins, mop floors with a disinfectant cleaner and clean glass partitions.",
      ]},
      { type: "h2", text: "Stock the essentials" },
      { type: "p", text: "Keep sanitizer at the entrance and on every floor, hand wash at every washroom basin, and glass cleaner for the many glass surfaces modern offices have. A multi-purpose cleaner handles most other surfaces efficiently." },
      { type: "quote", text: "Every rupee spent on workplace hygiene saves far more in reduced sick days and higher productivity." },
      { type: "p", text: "DPT Home Care supplies offices and corporates with reliable, bulk-quantity hygiene products — from sanitizers and hand wash to floor and glass cleaners — keeping your workplace spotless and your team protected." },
    ],
  },
  {
    slug: "daily-cleaning-checklist",
    title: "The Daily Cleaning Checklist Every Home Needs",
    excerpt:
      "Stop cleaning in exhausting weekend marathons. This simple daily checklist keeps your home consistently clean in just minutes a day.",
    category: "Routine",
    author: "DPT Home Care Team",
    date: "2025-04-28",
    readTime: "4 min read",
    image: IMG.cozyHome,
    keywords: ["daily cleaning checklist", "cleaning routine", "house cleaning schedule", "home cleaning tips"],
    content: [
      { type: "p", text: "The secret to an always-tidy home isn't a heroic weekend clean — it's a handful of small daily habits. Spread across the day, these tasks take just minutes but keep your home consistently fresh and hygienic. Here's the checklist to follow." },
      { type: "h2", text: "Morning (10 minutes)" },
      { type: "ul", items: [
        "Make the beds and open the windows for fresh air.",
        "Wipe kitchen counters and the dining table.",
        "Quickly wipe the bathroom basin and mirror.",
      ]},
      { type: "h2", text: "Through the day (as you go)" },
      { type: "ul", items: [
        "Wash utensils right after meals instead of piling them up.",
        "Wipe spills the moment they happen.",
        "Return items to their place to avoid clutter.",
      ]},
      { type: "h2", text: "Evening (15 minutes)" },
      { type: "ul", items: [
        "Sweep or mop high-traffic floors with a disinfectant cleaner.",
        "Disinfect high-touch surfaces — handles, switches, phones.",
        "Empty the kitchen bin and rinse it.",
        "A couple of sprays of room freshener before you relax.",
      ]},
      { type: "quote", text: "Ten minutes a day beats three hours on Sunday — and your home stays guest-ready all week." },
      { type: "h2", text: "Keep the right tools within reach" },
      { type: "p", text: "The easier cleaning is, the more likely you'll keep it up. Keep a multi-purpose cleaner, a microfibre cloth and a hand wash in every key area. DPT Home Care's everyday range is designed to make this daily routine effortless and affordable." },
    ],
  },
  {
    slug: "benefits-of-hand-wash",
    title: "Why Regular Hand Washing Matters: The Benefits of a Good Hand Wash",
    excerpt:
      "Hand washing is the simplest, most powerful way to prevent illness. Discover why it matters and how to choose the right hand wash.",
    category: "Personal Care",
    author: "DPT Home Care Team",
    date: "2025-05-14",
    readTime: "5 min read",
    image: IMG.handWash,
    keywords: ["benefits of hand wash", "hand washing", "hand hygiene", "germ protection"],
    content: [
      { type: "p", text: "It's the first thing we're taught as children and the advice health experts repeat most often: wash your hands. This simple habit is the single most effective way to stop the spread of germs and protect your family. Here's why it matters — and how to do it right." },
      { type: "h2", text: "Why hand washing is so effective" },
      { type: "p", text: "Our hands touch hundreds of surfaces every day, picking up germs that then reach our eyes, nose and mouth — and our food. Washing with a good hand wash physically removes these germs before they can cause illness." },
      { type: "h2", text: "Key benefits of using a quality hand wash" },
      { type: "ul", items: [
        "Removes germs, dirt and grease.",
        "Reduces the risk of common infections and stomach illness.",
        "Moisturising formulas keep skin soft, unlike harsh soaps.",
        "A pump dispenser is more hygienic than shared bar soap.",
        "A pleasant fragrance encourages the whole family to wash regularly.",
      ]},
      { type: "h2", text: "When you should always wash your hands" },
      { type: "ol", items: [
        "Before cooking, eating or handling food.",
        "After using the washroom.",
        "After returning home from outside.",
        "After coughing, sneezing or handling waste.",
      ]},
      { type: "h2", text: "Wash for at least 20 seconds" },
      { type: "p", text: "Lather all areas — palms, backs, between fingers and under nails — for at least 20 seconds before rinsing. When soap and water aren't available, use a 70% alcohol sanitizer as a backup." },
      { type: "quote", text: "Clean hands save lives. It's the cheapest, simplest health insurance your family can have." },
      { type: "p", text: "DPT Hand Wash combines effective germ protection with skin-loving moisturisers, available in Rose, Lemon, Aloe Vera and Sea Breeze — so hand hygiene feels as good as it works." },
    ],
  },
  {
    slug: "importance-of-toilet-cleaner",
    title: "The Importance of Using a Good Toilet Cleaner",
    excerpt:
      "The toilet is the most germ-dense spot in your home. Learn why a quality toilet cleaner is essential and how to use it effectively.",
    category: "Bathroom",
    author: "DPT Home Care Team",
    date: "2025-05-30",
    readTime: "5 min read",
    image: IMG.toiletBowl,
    keywords: ["toilet cleaner", "importance of toilet cleaner", "toilet hygiene", "germ free toilet"],
    content: [
      { type: "p", text: "It's not the most glamorous topic, but it's one of the most important. The toilet harbours more germs than almost anywhere else in your home, and a regular household cleaner simply isn't enough. Here's why a dedicated toilet cleaner is essential for a healthy home." },
      { type: "h2", text: "What's really lurking in your toilet" },
      { type: "p", text: "Toilets can harbour bacteria that cause serious stomach and intestinal infections. These germs can spread to hands and surfaces, especially around the seat, rim and flush button. A specialised toilet cleaner is formulated to destroy them." },
      { type: "h2", text: "Why an ordinary cleaner isn't enough" },
      { type: "ul", items: [
        "Toilet cleaners are thicker, so they cling and stay in contact longer.",
        "Their acidic formula dissolves limescale, rust and yellow stains.",
        "They are specifically designed to kill toilet germs.",
        "They neutralise the bacteria that cause persistent odour.",
      ]},
      { type: "h2", text: "How to use a toilet cleaner correctly" },
      { type: "ol", items: [
        "Squeeze the cleaner around and under the rim so it coats the inner bowl.",
        "Leave it for 5–10 minutes (longer for stubborn stains).",
        "Scrub thoroughly with a toilet brush, reaching under the rim.",
        "Flush to rinse and reveal a sparkling, hygienic bowl.",
      ]},
      { type: "quote", text: "A visibly clean toilet and a hygienic toilet are two different things — only a proper cleaner delivers both." },
      { type: "p", text: "DPT Toilet Cleaner is a thick, clinging formula that dissolves the toughest stains, kills germs and leaves a fresh pine fragrance. Use it two to three times a week for a consistently hygienic washroom." },
    ],
  },
  {
    slug: "how-to-keep-home-fresh",
    title: "How to Keep Your Home Smelling Fresh All Day",
    excerpt:
      "A fresh-smelling home feels clean and welcoming. Learn how to eliminate odours at the source and keep every room smelling wonderful.",
    category: "Fresh Home",
    author: "DPT Home Care Team",
    date: "2025-06-15",
    readTime: "5 min read",
    image: IMG.homePlants,
    keywords: ["keep home fresh", "home fragrance", "room freshener", "remove household odours"],
    content: [
      { type: "p", text: "Have you ever walked into a home that instantly felt clean and welcoming? Often it's not what you see — it's what you smell. A fresh-smelling home lifts the mood and signals cleanliness. Here's how to achieve lasting freshness in every room." },
      { type: "h2", text: "Eliminate odours at the source" },
      { type: "p", text: "Fragrance masks smells, but true freshness starts with removing the source. Tackle these common culprits first:" },
      { type: "ul", items: [
        "Empty and rinse kitchen bins daily.",
        "Clean the sink and drains, where food residue causes smells.",
        "Wash damp cloths, mats and towels regularly.",
        "Keep the bathroom clean and well-ventilated.",
      ]},
      { type: "h2", text: "Let fresh air circulate" },
      { type: "p", text: "Open windows for at least 15 minutes a day to clear stale air and moisture. Good ventilation is the free, natural foundation of a fresh home." },
      { type: "h2", text: "Layer in a lasting fragrance" },
      { type: "p", text: "Once the source is handled, add fragrance for that welcoming touch. A quality room freshener neutralises odour molecules rather than just covering them, leaving a clean scent that lingers." },
      { type: "ol", items: [
        "Spray a room freshener in living areas each morning.",
        "Use fabric conditioner so clothes and linens smell fresh for days.",
        "Mop floors with a fragranced floor cleaner for whole-room freshness.",
      ]},
      { type: "quote", text: "Freshness isn't about the strongest fragrance — it's about a clean base scent that makes your whole home feel cared for." },
      { type: "p", text: "DPT's Room Freshener range — Lavender, Citrus Bloom, Rose and Ocean — plus our fragranced floor cleaners and fabric conditioner, help you build lasting, layered freshness throughout your home." },
    ],
  },
  {
    slug: "cleaning-during-monsoon",
    title: "Monsoon Cleaning Guide: Keep Your Home Hygienic in the Rains",
    excerpt:
      "The monsoon brings dampness, mud and germs. This seasonal guide helps you keep your home clean, dry and healthy through the rainy season.",
    category: "Seasonal",
    author: "DPT Home Care Team",
    date: "2025-06-28",
    readTime: "6 min read",
    image: IMG.moppingBeige,
    keywords: ["monsoon cleaning", "rainy season cleaning", "prevent mould", "monsoon hygiene"],
    content: [
      { type: "p", text: "The monsoon is a welcome relief from the heat, but it brings its own hygiene challenges — muddy floors, damp corners, musty smells and a spike in germs and insects. With the right approach, you can keep your home clean, dry and healthy all season long." },
      { type: "h2", text: "Tackle mud and moisture at the entrance" },
      { type: "ul", items: [
        "Place absorbent mats at every doorway and clean them often.",
        "Mop entrance floors daily with a disinfectant floor cleaner.",
        "Keep a dedicated cloth to wipe muddy footprints quickly.",
      ]},
      { type: "h2", text: "Prevent mould and musty smells" },
      { type: "p", text: "Dampness encourages mould and bacteria. Fight back by keeping surfaces dry and disinfected:" },
      { type: "ol", items: [
        "Wipe damp walls and window sills regularly.",
        "Clean bathroom tiles and grout with a bathroom cleaner to stop mould.",
        "Use a room freshener to counter the musty monsoon smell.",
        "Let in sunlight and air whenever the rain pauses.",
      ]},
      { type: "h2", text: "Step up disinfection" },
      { type: "p", text: "Germs and infections rise during the monsoon. Increase how often you disinfect floors and high-touch surfaces, and keep hand wash and sanitizer readily available for the whole family." },
      { type: "h2", text: "Protect against insects" },
      { type: "p", text: "Standing water and food residue attract insects. Clean drains with phenyl, keep the kitchen spotless, and avoid leaving damp cloths around." },
      { type: "quote", text: "In the monsoon, dryness is hygiene. A dry, disinfected surface gives germs and mould nowhere to grow." },
      { type: "p", text: "DPT Home Care's disinfectant floor cleaner, phenyl, bathroom cleaner and room fresheners give you everything you need to keep your home hygienic and fresh right through the rainy season." },
    ],
  },
  {
    slug: "best-household-cleaning-products",
    title: "Best Household Cleaning Products Every Indian Home Needs",
    excerpt:
      "Overwhelmed by cleaning product choices? Here are the essential cleaners every home needs — and how to use each one effectively.",
    category: "Buying Guide",
    author: "DPT Home Care Team",
    date: "2025-07-18",
    readTime: "7 min read",
    image: IMG.cleaningProducts,
    keywords: ["best household cleaning products", "cleaning products list", "home cleaning essentials", "cleaning supplies india"],
    content: [
      { type: "p", text: "Walk down any cleaning aisle and the choices are overwhelming. But you don't need dozens of products — just the right essentials, each doing its job well. Here's the definitive list of cleaning products every Indian home needs, and how to get the most from each." },
      { type: "h2", text: "The 8 essentials for every home" },
      { type: "ol", items: [
        "Floor Cleaner — for daily disinfected, fragrant floors across the whole house.",
        "Toilet Cleaner — a thick, germ-killing formula for a hygienic washroom.",
        "Bathroom Cleaner — removes soap scum and hard-water marks from tiles and fittings.",
        "Dish Wash Liquid — cuts kitchen grease and keeps utensils shining.",
        "Glass Cleaner — for streak-free mirrors, windows and glass surfaces.",
        "Hand Wash — germ protection with moisturising care at every basin.",
        "Multi-Purpose Cleaner — one versatile cleaner for many surfaces.",
        "Room Freshener — the finishing touch for a welcoming home.",
      ]},
      { type: "h2", text: "Nice-to-have extras" },
      { type: "ul", items: [
        "Liquid Detergent and Fabric Conditioner for laundry day.",
        "Kitchen Cleaner for heavy grease and chimney cleaning.",
        "Sanitizer for on-the-go hand hygiene.",
        "Car Shampoo for a weekend vehicle wash.",
      ]},
      { type: "h2", text: "How to choose quality over hype" },
      { type: "p", text: "Look for concentrated formulas (more washes per bottle), genuine disinfectant action, and trusted manufacturing. A slightly higher-quality product almost always works out cheaper per use because you need less of it." },
      { type: "quote", text: "You don't need a cupboard full of products — you need a handful of really good ones." },
      { type: "h2", text: "One brand, complete coverage" },
      { type: "p", text: "DPT Home Care manufactures all these essentials — 15 products covering floor, bathroom, kitchen, fabric, personal and air care. Buying a complete range from one trusted manufacturer means consistent quality, better value and simpler restocking. That's the Power of Hygiene, made simple." },
    ],
  },
];

export function getPost(slug: string): BlogPost | undefined {
  return blogPosts.find((p) => p.slug === slug);
}

export function getRelatedPosts(slug: string, limit = 3): BlogPost[] {
  const current = getPost(slug);
  const others = blogPosts.filter((p) => p.slug !== slug);
  if (!current) return others.slice(0, limit);
  const sameCat = others.filter((p) => p.category === current.category);
  const rest = others.filter((p) => p.category !== current.category);
  return [...sameCat, ...rest].slice(0, limit);
}
